import "../globals.css";
import Navbar from "@/components/Navbar"
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";

export const metadata = {
  title: "Solara",
  description: "Generated by create next app",
};

export default async function RootLayout({children, params}) {

  const locale = params.locale;
  const messages = await getMessages();

  return (
    
    <html lang={locale} dir={locale === 'ar' ? 'rtl' : 'ltr'}>
      <body>
      <NextIntlClientProvider messages={messages}>
        <div className="mx-auto max-w-4xl h-screen">
       <Navbar/>
        {children}
        </div>
        </NextIntlClientProvider>
      </body>
    </html>
  
  );
}
